apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels: { app: php }
  template:
    metadata:
      labels: { app: php }
    spec:
      containers:
      - name: php-fpm
        image: php:8.3-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /var/lib/php/sessions
          name: php-sessions
        - mountPath: /var/www/html
          name: code
      volumes:
      - name: php-sessions
        persistentVolumeClaim:
          claimName: php-sessions-pvc
      - name: code
        persistentVolumeClaim:
          claimName: code-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: webapp
spec:
  selector:
    app: php
  ports:
  - name: fpm
    port: 9000
    targetPort: 9000
  type: ClusterIP
