apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-balancer
  namespace: webapp
  labels:
    app: nginx-balancer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-balancer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx-balancer
    spec:
      containers:
      - name: nginx
        image: ivan11sa/proyecto-php-nginx:fix1
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: mariadb.webapp.svc.cluster.local
        - name: DB_USER
          value: root
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mariadb-root
              key: root-password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/conf.d
        - name: code
          mountPath: /var/www/html
      volumes:
      - name: conf
        configMap:
          name: nginx-balancer-conf
      - name: code
        persistentVolumeClaim:
          claimName: code-pvc
