apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-balancer-conf
  namespace: webapp
data:
  default.conf: |
    error_log  /dev/stderr  debug;
    access_log /dev/stdout;

    upstream php-upstream {
        server php-service:9000;
    }

    server {
        listen 80 default_server;
        server_name tickets-ivan-asir-2025.duckdns.org _;

        # Ajusta esta ruta al directorio que montas en tu Deployment
        root /var/www/html/Sanchez_Acuna_Ivan_Proyecto_IAW;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass php-upstream;
            fastcgi_read_timeout 60s;
        }

        # Seguridad: bloquea accesos a archivos ocultos salvo .well-known
        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
