name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: docker build -t ivansan11/proyecto-php-nginx:${{ github.sha }} .
      - name: Run tests (optional, for PHP)
        run: |
          docker run --rm ivansan11/proyecto-php-nginx:${{ github.sha }} php -l /var/www/html/index_test.php

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
      - name: Configure kubectl
        run: kubectl config set-cluster my-cluster --server=$K8S_SERVER --certificate-authority=$K8S_CA --embed-certs=true
      - name: Deploy to Kubernetes
