CREATE TABLE USUARIOS (
    ID INT(5) AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CORREO VARCHAR(100) NOT NULL UNIQUE,
    CONTRASEÑA VARCHAR(100) NOT NULL,
    ADMIN BIT NOT NULL DEFAULT 0 
);

CREATE TABLE PROVINCIAS (
    ID_PROVINCIA INT(5) AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PROVINCIA VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE INCIDENCIAS (
    ID_INCIDENCIA INT(5) AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NIVEL_PRIORIDAD ENUM('Baja', 'Media', 'Alta', 'Urgente') NOT NULL,
    ESTADO ENUM('Abierta', 'Cerrada') NOT NULL DEFAULT 'Abierta',
    ID_PROVINCIA INT(5) NOT NULL,
    ID INT(5) NOT NULL,
    FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIAS(ID_PROVINCIA),
    FOREIGN KEY (ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE COMENTARIOS (
    ID_COMENTARIO INT(5) AUTO_INCREMENT PRIMARY KEY,
    TEXTO TEXT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_INCIDENCIA INT(5) NOT NULL,
    ID INT(5) NOT NULL,
    FOREIGN KEY (ID_INCIDENCIA) REFERENCES INCIDENCIAS(ID_INCIDENCIA),
    FOREIGN KEY (ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE RESPONSABLES (
    ID_RESPONSABLE INT(5) AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_RESPONSABLE VARCHAR(100) NOT NULL,
    CORREO_RESPONSABLE VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE INCIDENCIAS_RESPONSABLES (
    ID_INCIDENCIA_RESPONSABLE INT(5) AUTO_INCREMENT PRIMARY KEY,
    ID_INCIDENCIA INT(5) NOT NULL,
    ID_RESPONSABLE INT(5) NOT NULL,
    FOREIGN KEY (ID_INCIDENCIA) REFERENCES INCIDENCIAS(ID_INCIDENCIA),
    FOREIGN KEY (ID_RESPONSABLE) REFERENCES RESPONSABLES(ID_RESPONSABLE)
);

INSERT INTO USUARIOS (NOMBRE, CORREO, CONTRASEÑA, ADMIN) VALUES
('Administrador', 'admin@example.com', 'ContraseñaAdmin1!', 1);

INSERT INTO PROVINCIAS (NOMBRE_PROVINCIA) VALUES
    ('Almería'),
    ('Cádiz'),
    ('Córdoba'),
    ('Granada'),
    ('Huelva'),
    ('Jaén'),
    ('Málaga'),
    ('Sevilla');
