name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ivan11sa/proyecto-php-nginx
  K8S_NS: webapp                    # ← 1)  namespace a usar SIEMPRE

jobs:
# ────────────────────────────────────────────────────────────────────────────────
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push image
      run: |
        TAG=${GITHUB_SHA::7}
        docker build -t $REGISTRY/$IMAGE_NAME:$TAG .
        docker push  $REGISTRY/$IMAGE_NAME:$TAG
        echo "$TAG" > image_tag.txt

    - uses: actions/upload-artifact@v4
      with:
        name: image_tag
        path: image_tag.txt

# ────────────────────────────────────────────────────────────────────────────────
  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: image_tag
        path: .

    - uses: azure/setup-kubectl@v3

    # omite este paso si el runner ya tiene ~/.kube/config correcto
    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.K8S_CONFIG }}" | base64 -d > $HOME/.kube/config

    # 2)  Todas las órdenes kubectl van con -n "$K8S_NS"
    - name: Rollout both deployments
      id: rollout
      run: |
        TAG=$(cat image_tag.txt)
        kubectl -n "$K8S_NS" set image deployment/nginx-balancer   nginxr=$REGISTRY/$IMAGE_NAME:$TAG
        kubectl -n "$K8S_NS" set image deployment/php-deployment php=$REGISTRY/$IMAGE_NAME:$TAG
        kubectl -n "$K8S_NS" rollout status deployment/nginx-balancer   --timeout=5m
        kubectl -n "$K8S_NS" rollout status deployment/php-deployment --timeout=5m

    - name: Rollback if rollout fails
      if: failure()
      run: |
        echo "❌ Rollout failed. Reverting..."
        kubectl -n "$K8S_NS" rollout undo deployment/nginx-balancer
        kubectl -n "$K8S_NS" rollout undo deployment/php-deployment
