# .github/workflows/ci-cd.yaml.
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ivan11sa/proyecto-php-nginx
  IMAGE_TAG: ${{ github.sha }}
  K8S_NS: webapp

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Image
        shell: bash
        run: |
          TAG=$IMAGE_TAG
          docker build -t $REGISTRY/$IMAGE_NAME:$TAG .
          docker push $REGISTRY/$IMAGE_NAME:$TAG
          echo "IMAGE_TAG=$TAG" > image_tag.env

      - name: Upload image tag
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: image_tag.env

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download image tag
        uses: actions/download-artifact@v4
        with:
          name: image-tag
          path: .

      - name: Load IMAGE_TAG
        shell: bash
        run: |
          source image_tag.env
          echo "Deploying $REGISTRY/$IMAGE_NAME:$IMAGE_TAG to namespace $K8S_NS"

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        shell: bash
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.K8S_CONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Patch PHP Deployment image
        shell: bash
        run: |
          kubectl -n $K8S_NS set image deployment/php-deployment \
            php-fpm=$REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          kubectl -n $K8S_NS rollout status deployment/php-deployment --timeout=5m

      - name: Patch Nginx Deployment image
        shell: bash
        run: |
          kubectl -n $K8S_NS set image deployment/nginx-balancer \
            nginx=$REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          kubectl -n $K8S_NS rollout status deployment/nginx-balancer --timeout=5m

      - name: Rollback on failure
        if: failure()
        shell: bash
        run: |
          echo "❌ Rollout failed — undoing"
          kubectl -n $K8S_NS rollout undo deployment/php-deployment
          kubectl -n $K8S_NS rollout undo deployment/nginx-balancer
