name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -f ./Sánchez_Acuña_Iván_Proyecto_IAW/Dockerfile -t ivan11sa/proyecto-php-nginx:${{ github.sha }} .
        docker push ivan11sa/proyecto-php-nginx:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: build  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Set up kubeconfig
      run: |
        # Crear el directorio .kube si no existe
        mkdir -p $HOME/.kube
        
        # Escribir el kubeconfig completo con CA, token y contexto ya configurados
        echo "${{ secrets.K8S_CONFIG }}" > $HOME/.kube/config

        # Validar conexión con el clúster
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/nginx-deployment nginx=ivan11sa/proyecto-php-nginx:${{ github.sha }}
        kubectl rollout status deployment/nginx-deployment